name: Node.js CI

on:
    push:
        branches: ["login", "master"]
    pull_request:
        branches: ["login", "master"]

jobs:
    build:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Copy build files to EC2
              run: |
                  scp -o StrictHostKeyChecking=no -r ./Server ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/Server

            - name: Restart App on EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                  cd /home/ubuntu/Server
                  npm install --production
                  pm2 restart all || pm2 start index.js --name dashboard "ServerApp" -- start
                  EOF
